name: Main workflow
on: push
jobs:
  Build:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Clone down repository
        uses: actions/checkout@v4       
      - run: ci/build-app.sh
      - name: Run unit test Test
        run: ci/unit-test-app.sh
      - name: Upload repo (upload a Build Artifact) # Name of the step
        uses: actions/upload-artifact@v4 # Action to use
        with: # Parameters for the action
            name: CODE # Name of the artifact to upload. Optional. The default is 'artifact
            path: . # A file, directory, or wildcard pattern that describes what to upload. Required.
  Linting:
    runs-on: ubuntu-latest
    needs: [Build]
    steps:
      - name: Download code
        uses: actions/download-artifact@v4
        with:
          name: CODE # name of artifact to download
          path: . # where to download it to
      - name: Run linting
        uses: super-linter/super-linter-slim@v5
        env:
          DEFAULT_BRANCH: main
          # To report GitHub Actions status checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
